server:
  port: 9002
spring:
  application:
    name: myshop-web
eureka:
  client:
    register-with-eureka: true # ??????????Eureka
    fetch-registry: true  # ????????Eureka??????
    service-url: # ???????
      defaultZone: http://localhost:8888/eureka
  instance:
  # ????????IP?????Eureka??????????true
  prefer-ip-address: true
feign:
  circuitbreaker:
    enable: true # 开启 Feign 的熔断功能
